"""empty message

Revision ID: 4f2ca73e85ba
Revises: 
Create Date: 2017-03-03 16:37:20.456942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2ca73e85ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uber_access_token', sa.String(length=120), nullable=True),
    sa.Column('uber_refresh_token', sa.String(length=120), nullable=True),
    sa.Column('uber_client_id', sa.String(length=120), nullable=True),
    sa.Column('uber_expires_in_seconds', sa.String(length=120), nullable=True),
    sa.Column('uber_grant_type', sa.String(length=120), nullable=True),
    sa.Column('lyft_access_token', sa.String(length=120), nullable=True),
    sa.Column('lyft_refresh_token', sa.String(length=120), nullable=True),
    sa.Column('lyft_client_id', sa.String(length=120), nullable=True),
    sa.Column('lyft_expires_in_seconds', sa.String(length=120), nullable=True),
    sa.Column('lyft_grant_type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lyft_access_token'),
    sa.UniqueConstraint('lyft_client_id'),
    sa.UniqueConstraint('lyft_expires_in_seconds'),
    sa.UniqueConstraint('lyft_grant_type'),
    sa.UniqueConstraint('lyft_refresh_token'),
    sa.UniqueConstraint('uber_access_token'),
    sa.UniqueConstraint('uber_client_id'),
    sa.UniqueConstraint('uber_expires_in_seconds'),
    sa.UniqueConstraint('uber_grant_type'),
    sa.UniqueConstraint('uber_refresh_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
