"""empty message

Revision ID: 9fed11fc3929
Revises: 
Create Date: 2017-02-22 17:23:13.587843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fed11fc3929'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uber_access_token', sa.String(length=120), nullable=True),
    sa.Column('uber_refresh_token', sa.String(length=120), nullable=True),
    sa.Column('uber_client_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uber_access_token'),
    sa.UniqueConstraint('uber_client_id'),
    sa.UniqueConstraint('uber_refresh_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
