access_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsicHJvZmlsZSIsInBsYWNlcyIsInJlcXVlc3QiLCJyZXF1ZXN0X3JlY2VpcHQiLCJhbGxfdHJpcHMiLCJoaXN0b3J5Il0sInN1YiI6ImFkYWEzNWJmLTY4NTEtNDBiNC1hMmI2LTY3NzMxNzllYTJmZiIsImlzcyI6InViZXItdXMxIiwianRpIjoiMzJhMjA0YzgtM2IyYS00ZDgwLTkyMjctZDkyN2YxMTZkNDNlIiwiZXhwIjoxNDkwMTE1NDgxLCJpYXQiOjE0ODc1MjM0ODEsInVhY3QiOiJzNVFnVUhtQTk4R0tIS2RGWjA3TUU2N1lnYVM4ak8iLCJuYmYiOjE0ODc1MjMzOTEsImF1ZCI6InJvVmZkVHR4YkJjbnZqS2hpOGNXRWhSQy1zQXFCNlkwIn0.QqgeIjU8N4SRq2qj-yUGe5_4JuMYfuMbsyG0nBzEaFDCaNiWQ0JFEbVkY61vRpfJHhxcktgfhxSl0E3xVD6M96R_apiMuiLGLecQZdX7ddZEIzFB7m5jwcyYpYphkcZNnGl7FatTkuA5xqKLpg8XHvo5RXtro1TdYWgwWUogZRTHaYhTY9oNGIcU0q2rKOpEucWGkTVqM06kTvW_TL3IhpcIXZ07GlwEwUB6mdMhRWPPJgTWjYWsyqVPyRkonZ1tfd8wmIKX1C8xPVS4mVpnykJEDPktLlASAnemfv-e8b6GcaVGxBlp0_CCh6iznkwLI2OScIjUzWaDbaR-1bHjhQ
client_id: roVfdTtxbBcnvjKhi8cWEhRC-sAqB6Y0
client_secret: hA_d5ObgPaP6jWpMnHFaSg-doMODCaIFOxb05d5L
expires_in_seconds: 1490115481
grant_type: authorization_code
redirect_url: https://vtc-aggregator.herokuapp.com/api/uber/oauth
refresh_token: gwtNAH57S1dIoswe3U7bgRSVCUHkZm
scopes:
- profile
- places
- request
- request_receipt
- all_trips
- history
